---
- hosts: all
  become: yes
  tasks:
  - package:
      name: ["wget", "curl", "telnet"]
      state: present
  - package: 
      name: httpd
      state: present
    when: ansible_distribution|lower == 'CentOS'
  - package:
      name: apache2
      state: present
    when: ansible_distribution|lower != 'centos'
    #when: ansible_distribution == 'Ubuntu'
...

